version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: processing-py-site
    platform: linux/amd64
    volumes:
      - .:/usr/src/app

  fetch-jar:
    image: processing-py-site
    platform: linux/amd64
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "./fetch_processing_jar.sh"

  build-site:
    image: processing-py-site
    command: python generator.py build

  build-all:
    image: processing-py-site
    command: python generator.py build --all --images

  serve:
    image: processing-py-site
    volumes:
      - ./generated:/usr/src/app/generated
    ports:
      - "8080:80"
    command: sh -c "cd generated && python -m SimpleHTTPServer 80"
