[build]
  # Specify the build command you want to run
  command = "bash -c './fetch_processing_jar.sh && python generator.py build --all --images'"
  # Specify the directory that Netlify should publish
  publish = "generated"